
import { AccountingTerm } from './types';

export const ACCOUNTING_TERMS: AccountingTerm[] = [
  { abbr: "A", de: "Abschnitt", ar: "قسم / مقطع" },
  { abbr: "AB", de: "Anfangsbestand", ar: "رصيد أول المدة" },
  { abbr: "AfA", de: "Absetzung für Abnutzung", ar: "اهتلاك الأصول / الاستهلاك" },
  { abbr: "AG", de: "Aktiengesellschaft", ar: "شركة مساهمة" },
  { abbr: "AktG", de: "Aktiengesetz", ar: "قانون الشركات المساهمة" },
  { abbr: "AK", de: "Anschaffungskosten", ar: "تكاليف الشراء / الحيازة" },
  { abbr: "aLuL", de: "aus Lieferungen und Leistungen", ar: "من التوريدات والخدمات" },
  { abbr: "AN", de: "Arbeitnehmer", ar: "موظف / عامل" },
  { abbr: "ANK", de: "Anschaffungsnebenkosten", ar: "تكاليف الشراء الإضافية" },
  { abbr: "AO", de: "Abgabenordnung", ar: "قانون الضرائب" },
  { abbr: "AR", de: "Ausgangsrechnung", ar: "فاتورة صادرة" },
  { abbr: "AV", de: "Anlagevermögen", ar: "الأصول الثابتة" },
  { abbr: "B", de: "Berichtigungsschlüssel", ar: "مفتاح التصحيح" },
  { abbr: "BA", de: "Betriebsausgaben", ar: "مصاريف تشغيلية" },
  { abbr: "BGB", de: "Bürgerliches Gesetzbuch", ar: "القانون المدني" },
  { abbr: "BMF", de: "Bundesministerium der Finanzen", ar: "وزارة المالية الاتحادية" },
  { abbr: "BV", de: "Betriebsvermögen", ar: "أصول الشركة" },
  { abbr: "BWA", de: "Betriebswirtschaftliche Auswertung", ar: "التقييم الاقتصادي للأعمال" },
  { abbr: "DATEV", de: "Datenverarbeitungsorganisation", ar: "منظمة معالجة البيانات للمحاسبين" },
  { abbr: "DB", de: "Der Betrieb", ar: "المؤسسة / المنشأة" },
  { abbr: "e.K.", de: "eingetragener Kaufmann", ar: "تاجر مسجل" },
  { abbr: "EK", de: "Eigenkapital", ar: "رأس المال الخاص" },
  { abbr: "ER", de: "Eingangsrechnung", ar: "فاتورة واردة" },
  { abbr: "ESt", de: "Einkommensteuer", ar: "ضريبة الدخل" },
  { abbr: "EU", de: "Europäische Union", ar: "الاتحاد الأوروبي" },
  { abbr: "EStG", de: "Einkommensteuergesetz", ar: "قانون ضريبة الدخل" },
  { abbr: "FA", de: "Finanzamt", ar: "مصلحة الضرائب" },
  { abbr: "FK", de: "Fremdkapital", ar: "رأس المال الأجنبي / الخصوم" },
  { abbr: "GewSt", de: "Gewerbesteuer", ar: "ضريبة المهن / التجارة" },
  { abbr: "GmbH", de: "Gesellschaft mit beschränkter Haftung", ar: "شركة ذات مسؤولية محدودة" },
  { abbr: "GoB", de: "Grundsätze ordnungsgemäßer Buchführung", ar: "مبادئ المحاسبة السليمة" },
  { abbr: "GuV", de: "Gewinn- und Verlustrechnung", ar: "حساب الأرباح والخسائر" },
  { abbr: "GWG", de: "geringwertiges Wirtschaftsgut", ar: "سلعة اقتصادية منخفضة القيمة" },
  { abbr: "H", de: "Haben", ar: "دائن" },
  { abbr: "HB", de: "Handelsbilanz", ar: "الميزانية التجارية" },
  { abbr: "HGB", de: "Handelsgesetzbuch", ar: "القانون التجاري" },
  { abbr: "HK", de: "Herstellungskosten", ar: "تكاليف التصنيع" },
  { abbr: "HR", de: "Handelsregister", ar: "السجل التجاري" },
  { abbr: "KSt", de: "Körperschaftsteuer", ar: "ضريبة الشركات" },
  { abbr: "KV", de: "Krankenversicherung", ar: "التأمين الصحي" },
  { abbr: "LSt", de: "Lohnsteuer", ar: "ضريبة الرواتب" },
  { abbr: "MwSt", de: "Mehrwertsteuer", ar: "ضريبة القيمة المضافة" },
  { abbr: "RV", de: "Rentenversicherung", ar: "تأمين التقاعد" },
  { abbr: "S", de: "Soll", ar: "مدين" },
  { abbr: "SB", de: "Schlussbestand", ar: "رصيد آخر المدة" },
  { abbr: "SKR", de: "Spezialkontenrahmen", ar: "إطار الحسابات المتخصص" },
  { abbr: "USt", de: "Umsatzsteuer", ar: "ضريبة المبيعات" },
  { abbr: "USt-IdNr.", de: "Umsatzsteuer-Identifikationsnummer", ar: "الرقم الضريبي للقيمة المضافة" },
  { abbr: "UV", de: "Umlaufvermögen", ar: "الأصول المتداولة" },
  { abbr: "VoSt", de: "Vorsteuer", ar: "الضريبة المسبقة / المدخلات" },
  { abbr: "WG", de: "Wechselgesetz", ar: "قانون الكمبيالات" }
];
